#!/bin/bash
#PBS -l nodes=4:ppn=4
#PBS -l walltime=20:00:00
#PBS -l mem=120GB
#PBS -N dfdDenoiseWrapper
#PBS -M ek99@nyu.edu
#PBS -j oe

module load matlab/2014a

cd /scratch/ek99/denoiseproject/

# If the files you are running are not in the same folder as this script,
# you can insert "addpath(genpath('/PATH/TO/FILES/'));" before the command
# you want to run.
matlab -nodisplay -r "addpath(genpath('/scratch/ek99/denoiseproject')); dfdAddPaths; dfdDenoiseWrapper(1:8); exit()"

exit

