#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=5:00:00
#PBS -l mem=2GB
#PBS -N dfdDenoiseScript
#PBS -M ek99@nyu.edu
#PBS -j oe

module load matlab/2014a

cd /scratch/ek99/denoiseproject/

# If the files you are running are not in the same folder as this script,
# you can insert "addpath(genpath('/PATH/TO/FILES/'));" before the command
# you want to run.
matlab -nodisplay -r "dfdAddPaths; dfdDenoiseWrapper; exit()"

exit

